// Mock Seed Dataset for MediCompare Frontend Demo Fallback

export const MOCK_SERVICES = [
  { id: 1, name: 'MRI Scan', category: 'Radiology', description: 'Magnetic Resonance Imaging scan for detailed internal body imaging.' },
  { id: 2, name: 'CT Scan', category: 'Radiology', description: 'Computed Tomography scan for cross-sectional body imaging.' },
  { id: 3, name: 'X-Ray', category: 'Radiology', description: 'Standard diagnostic X-ray imaging.' },
  { id: 4, name: 'Blood Test', category: 'Pathology', description: 'Routine blood panel and diagnostic testing.' },
  { id: 5, name: 'Ultrasound', category: 'Radiology', description: 'Ultrasound imaging for soft tissue and organ examination.' },
  { id: 6, name: 'ECG', category: 'Cardiology', description: 'Electrocardiogram to check heart electrical activity.' },
  { id: 7, name: 'Health Checkup', category: 'General', description: 'Comprehensive full-body health checkup package.' },
  { id: 8, name: 'Dental Consultation', category: 'Dental', description: 'General dental consultation and checkup.' },
  { id: 9, name: 'General Consultation', category: 'General', description: 'Consultation with a general physician.' },
  { id: 10, name: 'Cardiology Consultation', category: 'Cardiology', description: 'Consultation with a cardiologist.' },
  { id: 11, name: 'Dermatology Consultation', category: 'Dermatology', description: 'Consultation with a dermatologist.' },
  { id: 12, name: 'Orthopedic Consultation', category: 'Orthopedics', description: 'Consultation with an orthopedic specialist.' },
  { id: 13, name: 'ENT Consultation', category: 'ENT', description: 'Consultation with an ENT specialist.' },
]

export const MOCK_HOSPITALS = [
  {
    id: 1,
    name: 'City Hospital & Research Centre',
    address: 'MG Road, Kanpur',
    city: 'Kanpur',
    locality: 'MG Road',
    latitude: 26.416685,
    longitude: 80.360277,
    rating: 4.4,
    reviewCount: 573,
    phone: '+91-7284887397',
    email: 'contact@cityhospital.demo',
    description: 'Multi-disciplinary care including ENT and cardiology services with 24x7 emergency support.',
    facilities: 'ICU,Pharmacy,Emergency Ward,24x7 Pharmacy,Blood Bank',
    specialties: 'Nephrology,Cardiology,Neurology,Gynecology',
    openingHours: '9:00 AM - 9:00 PM',
    available: true,
    verified: false,
  },
  {
    id: 2,
    name: 'Om Sai Healthcare',
    address: 'Baner, Kanpur',
    city: 'Kanpur',
    locality: 'Baner',
    latitude: 26.497854,
    longitude: 80.326078,
    rating: 3.6,
    reviewCount: 80,
    phone: '+91-8107812757',
    email: 'contact@omsai.demo',
    description: 'Multi-disciplinary care including nephrology and dental services with 24x7 emergency support.',
    facilities: 'Emergency Ward,Diagnostic Lab,ICU,Wheelchair Access,Cafeteria',
    specialties: 'Cardiology,Neurology,Orthopedics,Nephrology',
    openingHours: '8:00 AM - 10:00 PM',
    available: true,
    verified: false,
  },
  {
    id: 3,
    name: 'Metro General Hospital',
    address: 'Banjara Hills, Delhi',
    city: 'Delhi',
    locality: 'Banjara Hills',
    latitude: 28.671203,
    longitude: 77.124585,
    rating: 4.6,
    reviewCount: 611,
    phone: '+91-8810529410',
    email: 'contact@metrogeneral.demo',
    description: 'Premier medical centre with state-of-the-art radiology, surgery and outpatient consultation.',
    facilities: 'ICU,Blood Bank,Cafeteria,Parking,Diagnostic Lab',
    specialties: 'Gynecology,Neurology,Dental,Nephrology',
    openingHours: '24x7',
    available: true,
    verified: true,
  },
  {
    id: 4,
    name: 'Fortis Super Speciality Hospital',
    address: 'Sector 62, Noida',
    city: 'Noida',
    locality: 'Sector 62',
    latitude: 28.537393,
    longitude: 77.336511,
    rating: 4.5,
    reviewCount: 491,
    phone: '+91-9837847002',
    email: 'contact@fortisnoida.demo',
    description: 'Super speciality hospital offering high-end diagnostic scans, cardiac care and emergency trauma response.',
    facilities: 'Pharmacy,24x7 Pharmacy,Wheelchair Access,ICU,Ambulance',
    specialties: 'Neurology,Pediatrics,Dental,Gynecology',
    openingHours: '24x7',
    available: true,
    verified: true,
  },
  {
    id: 5,
    name: 'Grace Medical Centre',
    address: 'Andheri West, Mumbai',
    city: 'Mumbai',
    locality: 'Andheri West',
    latitude: 19.092140,
    longitude: 72.818266,
    rating: 4.3,
    reviewCount: 794,
    phone: '+91-9534732099',
    email: 'contact@gracemumbai.demo',
    description: 'Advanced medical centre in Mumbai offering affordable pricing across MRI, CT Scan and blood tests.',
    facilities: 'Wheelchair Access,Pharmacy,Ambulance,Blood Bank,Emergency Ward',
    specialties: 'ENT,Nephrology,Dental,Neurology',
    openingHours: '8:00 AM - 10:00 PM',
    available: true,
    verified: false,
  },
  {
    id: 6,
    name: 'Sunrise General Hospital',
    address: 'Koramangala, Bengaluru',
    city: 'Bengaluru',
    locality: 'Koramangala',
    latitude: 12.934152,
    longitude: 77.550386,
    rating: 4.7,
    reviewCount: 507,
    phone: '+91-8832735966',
    email: 'contact@sunriseblr.demo',
    description: 'Modern multispeciality hospital serving Bengaluru patients with quick slot booking and price transparency.',
    facilities: 'Diagnostic Lab,Emergency Ward,24x7 Pharmacy,Pharmacy,ICU',
    specialties: 'Pediatrics,ENT,Gynecology,General Medicine',
    openingHours: '24x7',
    available: true,
    verified: true,
  },
]

export const MOCK_PRICES = [
  // Hospital 1 - City Hospital Kanpur
  { hospitalId: 1, medicalServiceId: 1, price: 3800.0, available: true },
  { hospitalId: 1, medicalServiceId: 2, price: 2650.0, available: true },
  { hospitalId: 1, medicalServiceId: 3, price: 450.0, available: true },
  { hospitalId: 1, medicalServiceId: 4, price: 500.0, available: true },
  { hospitalId: 1, medicalServiceId: 5, price: 800.0, available: true },
  { hospitalId: 1, medicalServiceId: 6, price: 300.0, available: true },

  // Hospital 2 - Om Sai Kanpur
  { hospitalId: 2, medicalServiceId: 1, price: 3500.0, available: true },
  { hospitalId: 2, medicalServiceId: 2, price: 2600.0, available: true },
  { hospitalId: 2, medicalServiceId: 3, price: 400.0, available: true },
  { hospitalId: 2, medicalServiceId: 4, price: 450.0, available: true },
  { hospitalId: 2, medicalServiceId: 5, price: 750.0, available: true },

  // Hospital 3 - Metro General Delhi
  { hospitalId: 3, medicalServiceId: 1, price: 4200.0, available: true },
  { hospitalId: 3, medicalServiceId: 2, price: 2900.0, available: true },
  { hospitalId: 3, medicalServiceId: 3, price: 500.0, available: true },
  { hospitalId: 3, medicalServiceId: 4, price: 600.0, available: true },
  { hospitalId: 3, medicalServiceId: 7, price: 1800.0, available: true },

  // Hospital 4 - Fortis Noida
  { hospitalId: 4, medicalServiceId: 1, price: 4500.0, available: true },
  { hospitalId: 4, medicalServiceId: 2, price: 3100.0, available: true },
  { hospitalId: 4, medicalServiceId: 4, price: 650.0, available: true },
  { hospitalId: 4, medicalServiceId: 7, price: 2200.0, available: true },
  { hospitalId: 4, medicalServiceId: 10, price: 1000.0, available: true },

  // Hospital 5 - Grace Mumbai
  { hospitalId: 5, medicalServiceId: 1, price: 3900.0, available: true },
  { hospitalId: 5, medicalServiceId: 2, price: 2750.0, available: true },
  { hospitalId: 5, medicalServiceId: 5, price: 900.0, available: true },
  { hospitalId: 5, medicalServiceId: 8, price: 400.0, available: true },

  // Hospital 6 - Sunrise Bengaluru
  { hospitalId: 6, medicalServiceId: 1, price: 3600.0, available: true },
  { hospitalId: 6, medicalServiceId: 2, price: 2500.0, available: true },
  { hospitalId: 6, medicalServiceId: 4, price: 480.0, available: true },
  { hospitalId: 6, medicalServiceId: 7, price: 1600.0, available: true },
]

export const MOCK_DOCTORS = [
  { id: 1, hospitalId: 1, name: 'Dr. Rajesh Sharma', specialty: 'Cardiology', qualification: 'MD, DM Cardiology', experienceYears: 15, consultationFee: 800.0 },
  { id: 2, hospitalId: 1, name: 'Dr. Priya Verma', specialty: 'Radiology', qualification: 'MD Radiology', experienceYears: 10, consultationFee: 600.0 },
  { id: 3, hospitalId: 3, name: 'Dr. Anil Kapoor', specialty: 'Neurology', qualification: 'MBBS, DM Neurology', experienceYears: 18, consultationFee: 1000.0 },
  { id: 4, hospitalId: 4, name: 'Dr. Sunita Rao', specialty: 'General Physician', qualification: 'MBBS, MD General Medicine', experienceYears: 12, consultationFee: 700.0 },
  { id: 5, hospitalId: 6, name: 'Dr. Arvind Swamy', specialty: 'Pediatrics', qualification: 'MD Pediatrics', experienceYears: 14, consultationFee: 750.0 },
]

export const MOCK_REVIEWS = [
  { id: 1, hospitalId: 1, userName: 'Anand Kumar', rating: 5, comment: 'Very transparent pricing and clean facility. The MRI scan was done promptly.', createdAt: '2026-08-15', approved: true },
  { id: 2, hospitalId: 1, userName: 'Meera Patel', rating: 4, comment: 'Good service and courteous staff. Doctor was very helpful.', createdAt: '2026-08-20', approved: true },
  { id: 3, hospitalId: 3, userName: 'Rohan Gupta', rating: 5, comment: 'Booked slot through MediCompare and saved ₹700 compared to other local clinics.', createdAt: '2026-08-28', approved: true },
]

export const MOCK_USERS = [
  { id: 1, email: 'admin@medicompare.in', fullName: 'System Admin', role: 'ROLE_ADMIN', phone: '+91-9876543210', active: true },
  { id: 2, email: 'demo@medicompare.in', fullName: 'Demo Patient', role: 'ROLE_PATIENT', phone: '+91-9123456789', active: true },
]
